codecov: 
  token: 225403b5-5d60-4899-ba86-335be869d9c2

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach, diff, flags, files"
  behavior: default

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests/*"
  - "examples/*"

fixes:
  - "::src/"
  - "vortex_ws/src/*/vortex-auv/::"

flags:
  unittests:
    paths:
      - "tests/"
  integration:
    paths:
      - "tests/integration/"