name: black-format check

on: 
  workflow_call: #reusable workflow that can be called from other repos

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install deps
        run: pip install black 
        
      - name: Run Python black formatting check
        run: python3 -m black . --check --diff