name: Run Unit Test via Pytest

on: workflow_call

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install coverage-badge
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check . --format=github --target-version=py310
        continue-on-error: true
      - name: Test with Pytest
        run: |
         coverage run -m pytest -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m