name: Reusable ROS 2 Stonefish Simulator Test
on:
  workflow_call:
    inputs:
      os:
        description: "Operating System to run the workflow on"
        required: false
        default: "ubuntu-22.04"
        type: string
      ros_distro:
        description: "ROS 2 distribution to use"
        required: false
        default: "humble"
        type: string
      vcs_repos_file:
        description: "Path to the .repos file for dependencies"
        required: false
        default: "*.repos"
        type: string
      before_install_script:
        description: "Script to run before installing dependencies"
        required: false
        default: ""
        type: string
      test_script:
        description: "Test script to execute"
        required: true
        type: string
      skip_tests:
        description: "Skip running tests"
        required: false
        default: false
        type: boolean
jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}
    container:
      image: ros:${{ inputs.ros_distro }}-ros-base
    env:
      WORKSPACE: ~/ros2_ws
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ inputs.ros_distro }}
      # NEW: Copy the local repository into the workspace
      - name: Create workspace and copy local repository
        run: |
          mkdir -p $WORKSPACE/src
          cp -R $GITHUB_WORKSPACE/* $WORKSPACE/src/
      # Optional: Import additional dependencies from a .repos file
      - name: Import dependencies from .repos file (if provided)
        if: inputs.vcs_repos_file != ''
        run: |
          vcs import $WORKSPACE/src < ${{ inputs.vcs_repos_file }}
      - name: Verify Repository Cloning
        run: |
          echo "Checking imported repositories..."
          ls -R $WORKSPACE/src
      - name: Run pre-install script (if provided)
        if: inputs.before_install_script != ''
        run: |
          if [ -f "$GITHUB_WORKSPACE/${{ inputs.before_install_script }}" ]; then
            chmod +x "$GITHUB_WORKSPACE/${{ inputs.before_install_script }}"
            "$GITHUB_WORKSPACE/${{ inputs.before_install_script }}"
          else
            echo "Provided script does not exist: ${{ inputs.before_install_script }}"
          fi
      - name: Build ROS 2 workspace
        run: |
          cd $WORKSPACE
          . /opt/ros/${{ inputs.ros_distro }}/setup.sh
          colcon build
          . install/setup.bash
      - name: Run Test Script
        if: inputs.skip_tests == false
        run: |
          chmod +x "$GITHUB_WORKSPACE/${{ inputs.test_script }}"
          . /opt/ros/${{ inputs.ros_distro }}/setup.sh
          . $WORKSPACE/install/setup.bash
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
          "$GITHUB_WORKSPACE/${{ inputs.test_script }}"
      - uses: actions/upload-artifact@v4
        with:
          name: colcon-logs
          path: $WORKSPACE/log
        if: failure()
