name: Reusable ROS 2 Stonefish Simulator Test
on:
  workflow_call:
    inputs:
      os:
        description: "Operating System to run the workflow on"
        required: false
        default: "ubuntu-22.04"
        type: string
      ros_distro:
        description: "ROS 2 distribution to use"
        required: false
        default: "humble"
        type: string
      vcs_repos_file:
        description: "Path to the .repos file for dependencies"
        required: false
        default: "*.repos"
        type: string
      before_install_script:
        description: "Script to run before installing dependencies"
        required: false
        default: ""
        type: string
      test_script:
        description: "Test script to execute"
        required: true
        type: string
      skip_tests:
        description: "Skip running tests"
        required: false
        default: false
        type: boolean
jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}
    container:
      image: ros:${{ inputs.ros_distro }}-ros-base
    env:
      WORKSPACE: ~/ros2_ws # ✅ Now using ~/ros2_ws instead of $GITHUB_WORKSPACE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ inputs.ros_distro }}
      # ✅ Ensure workspace directories exist
      - name: Create ROS workspace structure
        run: |
          mkdir -p ~/ros2_ws/src
          mkdir -p ~/ros2_ws/build
          mkdir -p ~/ros2_ws/install
          mkdir -p ~/ros2_ws/log
      # ✅ Import dependencies using VCS
      - name: Import dependencies from .repos file
        if: inputs.vcs_repos_file != ''
        run: |
          vcs import ~/ros2_ws/src < ${{ inputs.vcs_repos_file }}
          rosdep update
          rosdep install --from-paths ~/ros2_ws/src --ignore-src -r -y
      # ✅ Debug Environment Variables
      - name: Debug Environment Variables
        run: env
      # ✅ Run pre-install script (if provided)
      - name: Run pre-install script (if provided)
        if: inputs.before_install_script != ''
        run: |
          cd ~/ros2_ws
          if [ -f "${{ inputs.before_install_script }}" ]; then
            chmod +x "${{ inputs.before_install_script }}"
            "${{ inputs.before_install_script }}"
          else
            echo "Provided script does not exist: ${{ inputs.before_install_script }}"
          fi
      # ✅ Check workspace structure
      - name: Check workspace structure
        run: |
          ls -la ~/ros2_ws
      # ✅ Build ROS 2 workspace
      - name: Build workspace
        shell: bash
        run: |
          cd ~/ros2_ws
          . /opt/ros/humble/setup.sh  # Source ROS 2

          # First, build Stonefish
          colcon build --packages-select stonefish_ros2 --symlink-install

          # Source and build the rest
          . install/setup.bash
          colcon build --packages-ignore stonefish_ros2 --symlink-install
      # ✅ Run Test Script
      - name: Run Test Script
        if: inputs.skip_tests == false
        run: |
          chmod +x "${{ inputs.test_script }}"
          . /opt/ros/${{ inputs.ros_distro }}/setup.sh
          . ~/ros2_ws/install/setup.bash
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
          "${{ inputs.test_script }}"
      # ✅ Upload build logs if failure
      - uses: actions/upload-artifact@v4
        with:
          name: colcon-logs
          path: ~/ros2_ws/log
        if: failure()
