name:
on:
    workflow_call:
        inputs:
            os_name:
                description: "Operating System to run the workflow on"
                required: false
                default: "ubuntu-22.04"
                type: string
            ros2_distro:
                description: "ROS 2 distribution to use"
                required: true
                type: string
            ref:
                description: "Git branch or tag to checkout"
                default: ${{ github.event.repository.default_branch }}
                required: false
                type: string
            python_version:
                description: "Python version to use"
                required: true
                type: string
            vcs_repo_file_url:
                description: "URL to the vcs repositories file"
                required: true
                type: string
            before_install_target_dependencies:
              description: "Command to run before installing target dependencies"
              required: false
              default: ""
              type: string

jobs:
  codecov:
    runs-on: ${{ inputs.os_name }}
    container:
      image: ros:${{ inputs.ros2_distro }}-ros-base
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        id: action_ros_ci_step
        with:
          required-ros-distributions: ${{ inputs.ros2_distro }}

      - name: Checkout repository
        uses: actions/checkout@v4
      - id: package_list_action
        uses: vortexntnu/vortex-ci/.github/actions/set-package-list@feat/codecov

      - name: Make script executable if provided
        if: inputs.before_install_target_dependencies != ''
        run: |
          if [ -f "${{ inputs.before_install_target_dependencies }}" ]; then
            echo "Making script executable: ${{ inputs.before_install_target_dependencies }}"
            chmod +x "${{ inputs.before_install_target_dependencies }}"
            ./${{ inputs.before_install_target_dependencies }}
          else
            echo "Provided path is not a file: ${{ inputs.before_install_target_dependencies }}"
          fi

      - name: Build and test ROS 2 packages
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ inputs.ros2_distro }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: ${{ steps.package_list_action.outputs.package_list }}
          vcs-repo-file-url: ${{ inputs.vcs_repo_file_url }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

      - name: Check code coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload logs
        uses: actions/upload-artifact@v4.4.3
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros_workspace_directory_name }}/log
        if: always()
