name: Reusable Semantic Release
on:
  workflow_call:
    inputs:
      os:
        description: "Operating System to run the workflow on"
        required: false
        default: "ubuntu-latest"
        type: string
      central_repo_name:
        description: "Repo name containing this workflow"
        required: false
        default: "vortexntnu/vortex-ci"
        type: string
      central_repo_ref:
        description: "Branch or tag to checkout in the central repo"
        required: false
        default: "main"
        type: string
      default_branch:
        description: "Default branch of the repository"
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
jobs:
  semantic-release:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout central repo
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.central_repo_name }}
          ref: ${{ inputs.central_repo_ref }}
          path: .central
      - name: Copy .releaserc to local workspace
        run: cp .central/.releaserc .
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              '${{ inputs.default_branch }}',
            ]
