name: Reusable Semantic Release
# Reusable GitHub Actions workflow to run semantic-release on a repository
on:
  workflow_call:
    inputs:
      os_name:
        description: "Operating System to run the workflow on"
        required: false
        default: "ubuntu-latest"
        type: string
      default_branch:
        description: "Default branch of the repository"
        required: false
        default: ${{ github.event.repository.default_branch }}
        type: string
jobs:
  semantic-release:
    runs-on: ${{ inputs.os_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              '${{ inputs.default_branch }}',
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer,
            @semantic-release/release-notes-generator,
            @semantic-release/github
