name: "PR Sphinx Docs Check and Deploy"
on:
  push:
    branches:
      - main

jobs:
  # Build the sphinx docs
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/" 
    
      # Save HTML page artifact
      - name: "Upload Sphinx Artifact"
        # Specify id for referencing output artifact
        id: upload_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html/
      
  # Deploy artifact to github pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}  # Use id from "Deploy to GitHub Pages" step below
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v4