name: Source Build on Push
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble-ros-base
    env:
      TEMPORARY_REPO_PATH: repo
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          path: ${{ env.TEMPORARY_REPO_PATH }}
      - name: Execute dependency script if exists
        run: |
          SCRIPT_NAME=${{ env.TEMPORARY_REPO_PATH }}/scripts/orca/requirements.sh
          echo "Checking for ${SCRIPT_NAME}..."
          chmod +x "$SCRIPT_NAME"
          ./$SCRIPT_NAME
      - name: Build stonefish_ros2 first
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          vcs-repo-file-url: ${{ env.TEMPORARY_REPO_PATH }}/scripts/orca/dependencies.repos
          package-name: stonefish_ros2
          skip-tests: true
      - name: Build remaining packages
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          vcs-repo-file-url: ${{ env.TEMPORARY_REPO_PATH }}/scripts/orca/dependencies.repos
          skip-tests: true
      - name: Execute tests
        run: |
          cd ${{ env.TEMPORARY_REPO_PATH }}/scripts/orca
          chmod +x ${{ env.TEMPORARY_REPO_PATH }}/scripts/orca/simulator_test.sh
          ./${{ env.TEMPORARY_REPO_PATH }}/scripts/orca/simulator_test.sh
