name: Build ROS 2 Package
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ros:humble-ros-base
    env:
      TEMPORARY_REPO_PATH: repo
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.TEMPORARY_REPO_PATH }}
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Create workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cp -R $GITHUB_WORKSPACE ~/ros2_ws/src/
      - name: Clone vortex dependencies
        run: |
          cd ~/ros2_ws/src
          git clone https://github.com/vortexntnu/vortex-msgs.git
          git clone https://github.com/vortexntnu/vortex-auv.git
          git clone https://github.com/patrykcieslak/stonefish_ros2.git
          git clone https://github.com/vortexntnu/vortex-stonefish-sim.git
      - name: Install dependencies
        run: |
          cd ~/ros2_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
      - name: Build workspace
        run: |
          cd ~/ros2_ws
          . /opt/ros/humble/setup.sh
          colcon build --symlink-install
      - name: Execute scripts from local repository
        run: |
          chmod +x ${{ env.TEMPORARY_REPO_PATH }}/scripts/orca/*.sh
          for script in ${{ env.TEMPORARY_REPO_PATH }}/scripts/orca/*.sh; do
            echo "Executing $script"
            ./$script
          done
      - uses: actions/upload-artifact@v4
        with:
          name: colcon-logs
          path: ~/ros2_ws/log
        if: failure()
