name: Run Pre-Commit Update Workflow
# Update pre-commit config and create a pull request if changes are detected
on:
  schedule:
    - cron: "0 * * 1 *" # Run every month
jobs:
  call_reusable_workflow:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-update-pre-commit.yaml@main
    with:
      ref: ${{ github.ref }}
      python_version: '3.10'
      responsible: 'kluge7'
